#define NAME(x) \
  Hi x!

#define MAIN_BODY(COMPANY_NAME, REASON, TEAM) \
  Unfortunately, due to the severe financial situation at COMOANY_NAME as \
  REASON, we're having to cut down on our workforce. This impacts several \
  teams at out company, such as yours, TEAM. With that in mind, effective \
  immediately, we're terminating your employment.

#define CLOSING_STATEMENT(COMPANY_NAME) \
Bye, \
COMPANY_NAME \
\
PS.: Don't reply to this email, as it's autogenerated!
